{% set name = "nessai-bilby" %}
{% set version = "0.1.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nessai_bilby-{{ version }}.tar.gz
  sha256: 29d180a334d4f2135a92170b40ab5faef53771b5019b690ba0eaa936b1026004

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - bilby >=2.3.0
    - nessai
    - numpy
    - pandas
    - scipy

test:
  imports:
    - nessai_bilby
  commands:
    - pip check
    - python -m pytest tests/
  requires:
    - pip
    - pytest
  source_files:
    - tests
    - pyproject.toml

about:
  summary: Interface and plugin for using nessai in bilby
  home: https://github.com/bilby-dev/nessai-bilby
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mj-will
    - johnveitch
