{% set name = "nessai-bilby" %}
{% set version = "0.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nessai_bilby-{{ version }}.tar.gz
  sha256: fd550dff9158c72b0cdc67d212238d4b9d7eeb1a5b9b3661a2ae96d45fc961ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - bilby >=2.3.0
    - nessai
    - numpy
    - pandas
    - scipy

test:
  imports:
    - nessai_bilby
  commands:
    - pip check
    - python -m pytest tests/
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - tests
    - pyproject.toml

about:
  summary: Interface and plugin for using nessai in bilby
  home: https://github.com/bilby-dev/nessai-bilby
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mj-will
    - johnveitch
